#pragma once
#include <iostream>
#include <fstream>
#include <sstream>
#include <string>
#include <unordered_map>
#include <regex>
#include <codecvt>
#include <cctype>
#include <cwctype>
#include <vector>

using std::cout;
using std::endl;
using std::wifstream;
using std::wstring;
using std::unordered_map;
using std::wstring;
using std::wregex;
using std::cerr;
using std::copy_if;
using std::back_inserter;
using std::iswalnum;
using std::codecvt_utf8;
using std::wistringstream;
using std::wstring;
using std::wofstream;
using std::locale;
using std::codecvt_utf8;
using std::wcout;
using std::regex_search;
using std::getline;
using std::wsmatch;
using std::vector;